## hello world

### hello world

In [323]:
print ('hello world')

hello world


In [324]:
import numpy as np
import pandas as pd
import math
import plotly.express as px
import plotly.graph_objects as go

In [325]:
sum = 0
for i in range(101):
    sum= sum +i

print(sum)

5050


In [326]:
sum = 0
x= [10,20,30,40,50,60,70]
for i in range(0, len(x)):
    sum = sum + x[i]
 
print(sum/ len(x))

40.0


In [327]:
for i in range(2,10):
    print('%d단'%i)
    for j in range(1,10):
        k =i *j
        print(i ,'*', j ,'=',k )

2단
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
3단
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
4단
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
5단
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
6단
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
7단
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
8단
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
9단
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81


In [328]:
def hello():
    print('hello')

In [329]:
hello()

hello


In [330]:
import datetime as dt

In [331]:
now = dt.datetime.now()

In [332]:
now

datetime.datetime(2024, 10, 21, 4, 15, 4, 21927)

In [333]:
print(now.strftime('%y-%m-%d-%a'))

24-10-21-Mon


In [334]:
dob1 = dt.datetime(2000,5,17)

In [335]:
age = now.year - dob1.year
age

24

In [336]:
xv = np.array([1,2,3,4,5,6,7,8,9])
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [337]:
xv = np.arange(1,10)
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [338]:
xv = np.arange(10)
xv

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [339]:
xv[3]

3

In [340]:
xv[1:4]

array([1, 2, 3])

In [341]:
xm = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [342]:
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [343]:
xm=np.arange(1,10)
xm = xm.reshape(-1,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [344]:
xm.shape

(3, 3)

In [345]:
xm[:1]

array([[1, 2, 3]])

In [346]:
xm[1:2,0]

array([4])

In [347]:
xm[1,2] = 11
xm

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 7,  8,  9]])

In [28]:
x[0:5]

[0, 1, 2, 3, 4]

In [29]:
x[-5:-2]

[15, 16, 17]

In [30]:
xm


array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 7,  8,  9]])

In [31]:
x= (4,5,6)

In [32]:
tp1 = (1,)
tp1

(1,)

In [33]:
tp1[0]

1

In [34]:
import numpy as np

In [35]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
m = np.mean(a)
m

7.0

In [37]:
a = range(4)

In [38]:
a = np.arange(15)
a
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
mean_a = np.mean(a)
mean_a

7.0

In [40]:
a = range(4)
b = np.arange(4)
print(a)
print(b)

range(0, 4)
[0 1 2 3]


In [41]:
height = np.array([45,75,60,51,np.nan])
print(np.nanmean(height))

57.75


In [42]:
score = 50

In [43]:
if(score >= 90):
    print('a')
elif(score >= 80):
    print('b')
elif(score >=70):
    print('c')
elif(score >= 60):
    print('d')
else:
    print('f')

f


In [44]:
list = ['c', 'd', 'd']
for i in list:
    print(i)

c
d
d


In [45]:
import math

In [46]:
xsum =0; sqsum=0
x=[10,12,21]
for i in range(0,3):
    xsum = xsum + x[i]
    sqsum=sqsum+x[i]**2

mean = xsum/len(x)
var = sqsum/(len(x)-1)-(len(x)*mean**2)/(len(x)-1)
sd = math.sqrt(var)
print('mean:',round(mean,3), '분산:',round(var,3), 'sd:',round(sd,3))

mean: 14.333 분산: 34.333 sd: 5.859


In [47]:
def reg(x,y):
    xsum = 0; ysum =0; xsqusm=0;  ysqusm=0; xysum=0
    a=range(0, len(x))
    n=len(x)
    for i in a:
        xsum = xsum + x[i]
        xsqusm = xsqusm + x[i]**2
        ysum = ysum + y[i]
        ysqusm = ysqusm + y[i]**2
        xysum = xysum + x[i] *y[i]
    xmean=xsum/n
    ymean=ysum/n

    b1 = (xysum-n*xmean*ymean)/(xsqusm-n*xmean**2)
    b0 = (ymean-b1*xmean)

    if(b1>0):
        print('추정된 회귀식=',round(b0,3), '+',round(b1,3), 'x')
    elif(b1<0):
        print('추정된 회귀식=',round(b0,3), '-', round(b1,3), 'x')
    else:
        print('x')

In [48]:
x=[2,3,4,5,6]
y=[4,7,6,8,10]
reg(x,y)

추정된 회귀식= 1.8 + 1.3 x


In [49]:
isum = 0
x = range(1,101)
for i in x:
    isum = isum + x[i - 1]

print(isum)

5050


In [50]:
sqsum = 0
x = range(1,11)
for i in x:
    sqsum = sqsum + x[i - 1]**2

print(sqsum)

385


In [51]:
x = range(1,11)
for i in x:
    print(i**2)

1
4
9
16
25
36
49
64
81
100


In [52]:
xsum = 0
x = [10, 12 ,21]
for i in range (0, len(x)):
    xsum = xsum + x[i]
xmean = xsum / len(x)
print(xmean)

14.333333333333334


In [58]:
import math
xsum = 0
xsqsum = 0
x= [10, 12, 21]
for i in range(0,3):
    xsum = x[i] + xsum
    xsqsum = x[i]**2 + xsqsum

mean = xsum / len(x)
var = xsqsum / (len(x) - 1)-(len(x)*mean**2)/(len(x)-1)
sd = math.sqrt(var)
print('평균:',mean,'분산:',var,'표준편차:',sd)

평균: 14.333333333333334 분산: 34.333333333333314 표준편차: 5.859465277082314


In [63]:
import pandas as pd

In [262]:
x = np.array([10, 20, 30, 40, 50])
df = pd.DataFrame(x)
mean = x.mean()
sd = x.std()
var = x.var()
print('평균:',mean,'\n', '분산:',var,'\n', '표준편차:',round(sd,3))


평균: 30.0 
 분산: 200.0 
 표준편차: 14.142


In [89]:
data = {
    'x' : [73,77,68,62,72,80,76,64,70,72],
    'y' : [68,72,64,60,71,77,74,60,64,68]
}
df = pd.DataFrame(data)
df.corr()

,x,y
x,1.000000,0.962226
y,0.962226,1.000000


In [230]:
xm = np.arange(1,10)
xm = xm.reshape(-1,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [232]:
country_code = {'korea':82, 'us':1, 'china':86}
country_code

{'korea': 82, 'us': 1, 'china': 86}

In [234]:
len(country_code)

3

In [236]:
country_code['korea']

82

In [241]:
a = np.mat([[1,2],[3,4]])
print(a)
b = np.mat([[1,5],[5,1]])
print(b)

[[1 2]
 [3 4]]
[[1 5]
 [5 1]]


In [243]:
print(a*b)

[[11  7]
 [23 19]]


In [245]:
print(a.I)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [248]:
print(a.T)
np.eye(3)

[[1 3]
 [2 4]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [250]:
print(a*a.I)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [253]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [255]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [263]:
N = len(fish_data)
mean = fish_data.mean()
mean

4.0

In [268]:
fish_data.var(ddof=0)
fish_data.std(ddof=0)

1.0954451150103321

In [271]:
x = [1,2,3,4,5]
y = [10,11,12,13,14]
np.cov(x,y,ddof=1)

array([[2.5, 2.5],
       [2.5, 2.5]])

In [273]:
fish_5 = np.array([2,3,4,5,6])
fish_5

array([2, 3, 4, 5, 6])

In [275]:
np.random.choice(fish_5, size=1, replace=False)

array([5])

In [277]:
np.random.choice(fish_5, size=3, replace=False)

array([6, 2, 5])

In [278]:
np.random.seed(1)
np.random.choice(fish_5, size=3, replace=False)

array([4, 3, 6])

In [282]:
np.random.seed(1)
np.random.choice(fish_5, size=3, replace=True)

array([5, 6, 2])

In [283]:
import scipy.stats

In [304]:
p =0.3
rv = scipy.stats.bernoulli(p)

print(rv.pmf(0))
print(rv.cdf(1))
print(rv.mean())
print(rv.var())
print(rv.rvs(10))

0.7000000000000002
1.0
0.3
0.21
[1 0 0 1 0 0 0 1 0 0]


In [312]:
n = 10
p = 0.3
binom = scipy.stats.binom(n, p)

print(round(binom.pmf(3), 3))
print(round(1 - binom.cdf(5), 3))
print(round(binom.mean(), 3))
print(round(binom.var(), 3))
print(binom.rvs(10))

0.267
0.047
3.0
2.1
[2 1 1 3 0 5 4 0 2 2]


In [314]:
from scipy import stats

In [316]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])

In [318]:
stats.scoreatpercentile(fish_data_3, 25)

3.0

In [320]:
stats.scoreatpercentile(fish_data_3, 50)

5.0

In [321]:
x = [1,2,3,4,5]
y = [10,11,12,13,14]

In [322]:
N = len(x)
mu_x = x.mean()

AttributeError: 'list' object has no attribute 'mean'