In [9]:
import pandas as pd
import numpy as np
from scipy import stats
import math

In [10]:
def reg(x,y):
    xsum=0; ysum=0; xsqusm=0; ysqusm=0; xysum=0
    a = range(0,len(x))
    n = len(x)
    for i in a:
        xsum = xsum + x[i]
        ysum = ysum + y[i]
        xsqusm = xsqusm + x[i]**2
        ysqusm = ysqusm + y[i]**2
        xysum = xysum + x[i]*y[i]
    xmean = xsqusm / n
    ymean = ysqusm / n

    b1 = (xysum-n*xmean*ymean)/(xsqusm-n*xmean**2)
    b0 = (ymean - b1*xmean)

In [11]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [12]:
mean = fish_data.mean()
mean

4.0

In [13]:
var = fish_data.var(ddof=0)
var

1.2

In [14]:
std = fish_data.std()
std

1.0954451150103321

In [15]:
stats.scoreatpercentile(fish_data, 50)

4.0

In [16]:
data ={
    'x' : [1,2,3,4,5],
    'y' : [10, 11, 12, 13, 14]
}
df = pd.DataFrame(data)
df.corr()

,x,y
x,1.0,1.0
y,1.0,1.0


In [17]:
a = np.mat([[1,2], [3,4]])
b = np.mat([[1,5],[5,1]])

In [18]:
print(a*b)

[[11  7]
 [23 19]]


In [19]:
print(a.I) #역행렬

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
print(a.T) #행렬의 전치

[[1 3]
 [2 4]]


In [21]:
np.linalg.det(a) #행렬식

-2.0000000000000004

In [22]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [23]:
arr = [1,2,3,4,5,6]
sum(arr[::2])
sum(arr)

21

In [25]:
arr = range(1,10,1)
arr

range(1, 10)

In [29]:
import datetime as dt

In [35]:
now = dt.datetime.now()
print(now.year)

2024


In [1]:
print(now.strftime('%Y - %m - %d : %a'))

NameError: name 'now' is not defined

In [3]:
import numpy as np
from scipy import stats

In [ ]:
be_included_array = np.zeros(20000)
np.random.seed(1)
norm_dist = stats.norm(loc = 4, scale = 0.8)
for i in range(0, 20000):
    sample = norm_dist.rvs(size = 10)
    df = len(sample ) -1 
    mu = np.mean(sample)
    std = np.std(sample, ddof=1)
    se = std/np.sqrt(len(sample))
    interval = stats.t.interval(0.95, df, mu, se)
    if(interval[0]<=4 and interval[1] >=4):
        be_included_array[i] = True

In [7]:
sum(be_included_array)/ len(be_included_array)

0.948

In [1]:
import numpy as np
from scipy.stats import chi2_contingency
obs = np.array[[10,15], [20, 5]]

TypeError: 'builtin_function_or_method' object is not subscriptable