In [28]:
import numpy as np

In [29]:
A = np.array([[ 6, -2, -1],
              [-2, 6, -1],
              [-1, -1, 5]])

In [30]:
val, vet = np.linalg.eig(A)

In [31]:
print('val :')
print(val)

val :
[3. 8. 6.]


In [32]:
print('vet :')
print(vet)

vet :
[[ 5.77350269e-01  7.07106781e-01 -4.08248290e-01]
 [ 5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [ 5.77350269e-01  9.06835124e-17  8.16496581e-01]]


In [33]:
B = np.linalg.inv(A)
B

array([[0.20138889, 0.07638889, 0.05555556],
       [0.07638889, 0.20138889, 0.05555556],
       [0.05555556, 0.05555556, 0.22222222]])

In [34]:
A = np.array([[1,2,3,5],
              [0,1,3,3],
              [2,1,0,1],
              [0,1,2,2]])

In [35]:
B = np.linalg.inv(A)
B

array([[-3.33333333e-01,  1.00000000e+00,  6.66666667e-01,
        -1.00000000e+00],
       [ 2.96059473e-16, -2.00000000e+00, -1.48029737e-16,
         3.00000000e+00],
       [-6.66666667e-01,  1.00000000e+00,  3.33333333e-01,
         1.66533454e-16],
       [ 6.66666667e-01,  1.11022302e-16, -3.33333333e-01,
        -1.00000000e+00]])

In [36]:
val, vet = np.linalg.eig(A)

In [37]:
print(val)

[ 5.82535931+0.j         -0.63539643+0.72450408j -0.63539643-0.72450408j
 -0.55456644+0.j        ]


In [38]:
vet

array([[ 0.74855806+0.j        , -0.20240369-0.35421442j,
        -0.20240369+0.35421442j,  0.30462093+0.j        ],
       [ 0.43660132+0.j        ,  0.51657069+0.26337916j,
         0.51657069-0.26337916j, -0.82124807+0.j        ],
       [ 0.38620241+0.j        , -0.64026363+0.j        ,
        -0.64026363-0.j        ,  0.47943258+0.j        ],
       [ 0.31605035+0.j        ,  0.29505791-0.01882392j,
         0.29505791+0.01882392j, -0.05387102+0.j        ]])

In [ ]:
A = np.array([[7.14893617, 1.25531915, 0.23404255, 2.29787234, 0.59574468, 1.93617021, -0.72340426, 2.48936170, 4.85106383, 2.72340426, 2.23404255, 2.74468085, 3.12765957, 3.31914894, 5.17021277],
              [1.25531915, 3.86524823, 0.48226950, 2.09397163, 2.04787234, 2.31382979, 1.76241135, 3.25177305, 0.91666667, 1.97340426, 3.17198582, 3.02127660, 3.17553191 ,1.48404255 ,2.49290780], 
              [0.23404255, 0.48226950, 3.95035461, 0.00886525, 0.00531915, 0.48404255, -0.15248227, 0.31560284, 1.74645390, 0.54787234, 0.25709220, 1.19148936, 1.83510638, -1.70744681, 0.91843972],
                [2.29787234, 2.09397163, 0.00886525, 7.87189716, 2.05186170, 4.29388298, 4.58953901, 3.37145390, 1.30629433, 3.25132979, 2.85416667, 4.28191489, 5.40824468, 5.10771277, 3.02748227], 
                [0.59574468, 2.04787234, 0.00531915, 2.05186170, 5.84707447, 6.19015957, 2.51329787, 6.83776596, 0.12101064, 5.01994681, 5.97739362, 5.29255319, 5.17154255, 3.09973404, 1.99734043],
                [1.93617021, 2.31382979, 0.48404255, 4.29388298, 6.19015957, 10.04920213, 2.85904255, 9.06648936, 1.54388298, 6.51728723, 7.04920213, 8.49468085, 7.84441489, 4.43750000, 4.35372340],
                [-0.72340426, 1.76241135, -0.15248227, 4.58953901, 2.51329787, 2.85904255, 6.42375887, 2.03014184, -1.30762411, 2.09308511, 1.59663121, 2.96808511, 3.35372340, 3.01861702, 0.02304965],
                [2.48936170 3.25177305 0.31560284 3.37145390 6.83776596 9.06648936 2.03014184 11.99822695 2.66578014 8.27925532 8.74024823 8.05319149 8.10372340 5.05585106, 6.26773050], 
4.85106383 0.91666667 1.74645390 1.30629433 0.12101064 1.54388298 -1.30762411 2.66578014 10.94636525 3.28856383 1.89849291 3.00531915 3.66888298 1.88962766 7.56294326, 
2.72340426 1.97340426 0.54787234 3.25132979 5.01994681 6.51728723 2.09308511 8.27925532 3.28856383 8.68750000 6.75132979 6.38829787 7.39760638 4.79920213 6.05585106, 
2.23404255 3.17198582 0.25709220 2.85416667 5.97739362 7.04920213 1.59663121 8.74024823 1.89849291 6.75132979 8.61657801 6.98404255 7.18484043 4.26728723 4.21187943, 
2.74468085 3.02127660 1.19148936 4.28191489 5.29255319 8.49468085 2.96808511 8.05319149 3.00531915 6.38829787 6.98404255 9.21276596 8.46276596 4.43085106 5.28723404, 
3.12765957 3.17553191 1.83510638 5.40824468 5.17154255 7.84441489 3.35372340 8.10372340 3.66888298 7.39760638 7.18484043 8.46276596 10.13430851 4.56250000 6.02925532, 
3.31914894 1.48404255 -1.70744681 5.10771277 3.09973404 4.43750000 3.01861702 5.05585106 1.88962766 4.79920213 4.26728723 4.43085106 4.56250000 7.05984043 3.47074468, 
5.17021277 2.49290780 0.91843972 3.02748227 1.99734043 4.35372340 0.02304965 6.26773050 7.56294326 6.05585106 4.21187943 5.28723404 6.02925532 3.47074468 10.89184397 ])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (552981204.py, line 1)