In [1]:
import numpy as np

In [2]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [3]:
len(fish_data)

10

In [4]:
N = len(fish_data)
sum_value = np.sum(fish_data)
mu = sum_value/ N
mu

4.0

In [5]:
var = np.sum((fish_data - mu) **2)/N
var

1.2

In [6]:
np.var(fish_data)
np.var(fish_data, ddof=0) #ddof = 1 표본분산, 0 모분산

1.2

In [7]:
from scipy import stats

In [8]:
fish_data = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data, 75)

7.0

In [9]:
x= [1,2,3,4,5]
y = [10,11,12,13,14]

In [10]:
np.cov(x,y, ddof=0)

array([[2., 2.],
       [2., 2.]])

In [11]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats
from matplotlib import pyplot as plt
import seaborn as sns

In [12]:
fish_5 = np.array([2,3,4,5,6])
fish_5

array([2, 3, 4, 5, 6])

In [13]:
np.random.choice(fish_5, size = 3, replace=False)

array([2, 4, 6])

In [15]:
np.random.seed(1)
np.random.choice(fish_5, size=3, replace=False)

array([4, 3, 6])