In [3]:
import numpy as np
from scipy.stats import f

# 표본 크기
n1, n2 = 252, 154
p = 2  # 변수 개수

# 평균벡터
x1_bar = np.array([2.61, 2.63])
x2_bar = np.array([2.54, 2.55])

# 공분산 행렬
S1 = np.array([
    [0.260, 0.181],
    [0.181, 0.203]
])
S2 = np.array([
    [0.303, 0.206],
    [0.206, 0.194]
])

# 풀어진 공분산행렬 Sp
Sp = ((n1 - 1) * S1 + (n2 - 1) * S2) / (n1 + n2 - 2)

# 평균 차이 벡터
diff = x1_bar - x2_bar

# T² 통계량
T2 = (n1 * n2) / (n1 + n2) * diff.T @ np.linalg.inv(Sp) @ diff

# F 통계량으로 변환
F_stat = (n1 + n2 - p - 1) / (p * (n1 + n2 - 2)) * T2

# p-value 계산
p_val = 1 - f.cdf(F_stat, dfn=p, dfd=n1 + n2 - p - 1)

# 출력
print(f"T²: {T2:.3f}")
print(f"F: {F_stat:.3f}")
print(f"p-value: {p_val:.4f}")


T²: 3.106
F: 1.549
p-value: 0.2137


In [5]:
import numpy as np

# 표본 수
n1, n2 = 252, 154

# 두 그룹의 공분산행렬
S1 = np.array([
    [0.260, 0.181],
    [0.181, 0.203]
])
S2 = np.array([
    [0.306, 0.206],
    [0.206, 0.194]
])

# 풀어진 공분산행렬 S_p 계산 공식
Sp = ((n1 - 1) * S1 + (n2 - 1) * S2) / (n1 + n2 - 2)

# 출력
print("Sp =\n", np.round(Sp, 4))


Sp =
 [[0.2774 0.1905]
 [0.1905 0.1996]]


In [6]:
import numpy as np
from scipy.stats import f

# 표본 수
n1, n2 = 20, 30
p = 2  # 변수 수

# 평균벡터
x1_bar = np.array([78, 83])
x2_bar = np.array([84, 80])

# 공분산행렬
S1 = np.array([
    [33, 10],
    [10, 28]
])
S2 = np.array([
    [32, 23],
    [23, 42]
])

# 풀어진 공분산행렬 Sp
Sp = ((n1 - 1) * S1 + (n2 - 1) * S2) / (n1 + n2 - 2)

# 평균 차이 벡터
diff = x1_bar - x2_bar

# T² 통계량
T2 = (n1 * n2) / (n1 + n2) * diff.T @ np.linalg.inv(Sp) @ diff

# F 통계량으로 변환
F_stat = ((n1 + n2 - p - 1) / (p * (n1 + n2 - 2))) * T2

# p-value 계산
p_val = 1 - f.cdf(F_stat, dfn=p, dfd=n1 + n2 - p - 1)

# 결과 출력
print("Sp =\n", np.round(Sp, 3))
print(f"T² = {T2:.3f}")
print(f"F  = {F_stat:.3f}")
print(f"p-value = {p_val:.4f}")


Sp =
 [[32.396 17.854]
 [17.854 36.458]]
T² = 31.266
F  = 15.307
p-value = 0.0000


In [8]:
import numpy as np
from scipy.stats import chi2

# 표본 수
n1, n2 = 20, 30
p = 2  # 변수 수

# 평균벡터
x1_bar = np.array([78, 83])
x2_bar = np.array([84, 80])

# 공분산 행렬
S1 = np.array([
    [33, 10],
    [10, 28]
])
S2 = np.array([
    [32, 23],
    [23, 42]
])

# 평균 차이
diff = x1_bar - x2_bar

# 이분산 가정 하의 결합 공분산행렬 St
St = S1 / n1 + S2 / n2

# T² 통계량 계산
T2 = diff.T @ np.linalg.inv(St) @ diff

# 임계값 (chi²)
chi2_critical = chi2.ppf(1 - 0.05, df=p)

# p-value
p_val = 1 - chi2.cdf(T2, df=p)

# 출력
print("St =\n", np.round(St, 3))
print(f"T² = {T2:.3f}")
print(f"Chi² 임계값 (0.05) = {chi2_critical:.3f}")
print(f"p-value = {p_val:.4f}")


St =
 [[2.717 1.267]
 [1.267 2.8  ]]
T² = 28.464
Chi² 임계값 (0.05) = 5.991
p-value = 0.0000


In [9]:
import numpy as np
from scipy.stats import f

# 표본 수
n1 = n2 = 9
p = 2  # 변수 수

# 평균 벡터
x1_bar = np.array([13.5, 14.5])
x2_bar = np.array([12.0, 14.0])

# 공분산 행렬
S1 = np.array([
    [55.80, 10.26],
    [10.26, 60.73]
])
S2 = np.array([
    [102.60, 13.75],
    [13.75, 95.23]
])

# 풀어진 공분산 행렬 Sp
Sp = ((n1 - 1)*S1 + (n2 - 1)*S2) / (n1 + n2 - 2)

# 평균 차이
diff = x1_bar - x2_bar

# Hotelling T² 계산
T2 = (n1 * n2) / (n1 + n2) * diff.T @ np.linalg.inv(Sp) @ diff

# F 통계량 변환
F_stat = ((n1 + n2 - p - 1) / (p * (n1 + n2 - 2))) * T2

# p-value
p_val = 1 - f.cdf(F_stat, p, n1 + n2 - p - 1)

# 출력
print("Sp =\n", np.round(Sp, 3))
print(f"T² = {T2:.3f}")
print(f"F  = {F_stat:.3f}")
print(f"p-value = {p_val:.4f}")


Sp =
 [[79.2   12.005]
 [12.005 77.98 ]]
T² = 0.132
F  = 0.062
p-value = 0.9401
