In [12]:
import numpy as np
from scipy.stats import f

# 데이터 입력 (4개의 표본, 2개의 변수)
X = np.array([
    [166, 70],
    [170, 63],
    [158, 55],
    [175, 72],
    [180,70],
    [174,60],
    [180, 68],
    [177,62],
    [175,70]
])

# 기본 통계량
n, p = X.shape
X_bar = np.mean(X, axis=0)  # 표본 평균
S = np.cov(X, rowvar=False)  # 공분산 행렬

# 모평균 벡터
mu_0 = np.array([173, 64])

# Hotelling's T² statistic
diff = X_bar - mu_0
T2 = n * diff.T @ np.linalg.inv(S) @ diff

# F 분포로 변환
F_stat = (n - p) * T2 / (p * (n - 1))
p_value = 1 - f.cdf(F_stat, p, n - p)

# 결과 출력
print(f"T² = {T2:.4f}")
print(f"F = {F_stat:.4f}")
print(f"p-value = {p_value:.4f}")

# 유의수준 0.05에서의 결론
alpha = 0.05
if p_value < alpha:
    print("귀무가설 기각: 평균 벡터는 다릅니다.")
else:
    print("귀무가설 채택: 평균 벡터는 동일하다고 볼 수 있습니다.")


T² = 1.0847
F = 0.4746
p-value = 0.6408
귀무가설 채택: 평균 벡터는 동일하다고 볼 수 있습니다.


In [14]:
import numpy as np
from scipy.stats import f

# 데이터
X = np.array([
    [166, 70],
    [170, 63],
    [158, 55],
    [175, 72],
    [180,70],
    [174,60],
    [180, 68],
    [177,62],
    [175,70]
])
n, p = X.shape

# 공분산 행렬
S = np.cov(X, rowvar=False)

# 고유값과 고유벡터
eigvals, eigvecs = np.linalg.eigh(S)
# 큰 값을 λ1으로 정렬
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

lambda1, lambda2 = eigvals
e1, e2 = eigvecs[:, 0], eigvecs[:, 1]

# F값 (F_{2, 2}(0.05))
F_val = f.ppf(0.95, dfn=p, dfd=n-p)

# 장축 및 단축 길이
factor = ((n-1)*p)/(n*(n-p)) * F_val
major_axis = 2 * np.sqrt(lambda1 * factor)
minor_axis = 2 * np.sqrt(lambda2 * factor)

# 비율
axis_ratio = np.sqrt(lambda1 / lambda2)

# 결과 출력
print(f"장축 길이: {major_axis:.4f}")
print(f"단축 길이: {minor_axis:.4f}")
print(f"축 비율 (장/단): {axis_ratio:.4f}")
print(f"장축 방향벡터: {e1}")
print(f"단축 방향벡터: {e2}")


장축 길이: 17.9287
단축 길이: 9.1592
축 비율 (장/단): 1.9574
장축 방향벡터: [-0.82091134 -0.57105566]
단축 방향벡터: [ 0.57105566 -0.82091134]


In [18]:
import numpy as np

# 예제 데이터
X = np.array([
    [166, 70],
    [170, 63],
    [158, 55],
    [175, 72],
    [180, 70],
    [174, 60],
    [180, 68],
    [177, 62],
    [175, 70]
])
n = X.shape[0]

# 1. 표본 평균
X_bar = np.mean(X, axis=0)
print(X_bar)
# 2. 모평균
mu_0 = np.array([173, 64])

# 3. 표본 공분산 행렬
S = np.cov(X, rowvar=False)
print(S)
# 4. 차이 벡터
d = X_bar - mu_0

# 5. 공분산 행렬의 역행렬
S_inv = np.linalg.inv(S)

# 6. T^2 계산
T2 = n * d.T @ S_inv @ d
print(f"T² = {T2:.4f}")


[172.77777778  65.55555556]
[[50.69444444 23.13888889]
 [23.13888889 33.52777778]]
T² = 1.0847


In [20]:
import numpy as np

X = np.array([
    [166, 70],
    [170, 63],
    [158, 55],
    [175, 72],
    [180, 70],
    [174, 60],
    [180, 68],
    [177, 62],
    [175, 70]
])

# 1. 각 열별 평균을 구해 데이터 중앙정렬 (평균 0으로 맞춤)
X_centered = X - np.mean(X, axis=0)

# 2. 공분산 행렬 계산 (열 기준)
S = np.cov(X_centered, rowvar=False)

# 3. 고유값과 고유벡터 계산
eigenvalues, eigenvectors = np.linalg.eig(S)

print("공분산 행렬 S:\n", S)
print("고유값:\n", eigenvalues)
print("고유벡터:\n", eigenvectors)


공분산 행렬 S:
 [[50.69444444 23.13888889]
 [23.13888889 33.52777778]]
고유값:
 [66.79069357 17.43152866]
고유벡터:
 [[ 0.82091134 -0.57105566]
 [ 0.57105566  0.82091134]]


In [21]:
import numpy as np

X = np.array([
    [166, 70],
    [170, 63],
    [158, 55],
    [175, 72],
    [180, 70],
    [174, 60],
    [180, 68],
    [177, 62],
    [175, 70]
])

# 데이터 중앙정렬
X_centered = X - np.mean(X, axis=0)

# 공분산 행렬 계산
S = np.cov(X_centered, rowvar=False)

# 공분산 행렬의 역행렬 계산
S_inv = np.linalg.inv(S)

print("공분산 행렬 S:\n", S)
print("S의 역행렬 S_inv:\n", S_inv)


공분산 행렬 S:
 [[50.69444444 23.13888889]
 [23.13888889 33.52777778]]
S의 역행렬 S_inv:
 [[ 0.0287974  -0.01987426]
 [-0.01987426  0.04354206]]
